import { describe, expect, it } from 'vitest';

import {
  generateTokenSection,
  injectTokenSection,
  parseTokensJson,
  renderFullTokenDoc,
  type TokenFile,
} from '../src/design-system/index.js';

const TOKENS: TokenFile = {
  categories: [
    {
      name: 'Colors',
      description: 'Brand color palette',
      tokens: [
        { name: 'color-primary', value: '#0066FF', type: 'color', comment: 'Primary brand blue' },
        { name: 'color-danger', value: '#FF0000', type: 'color' },
      ],
    },
    {
      name: 'Spacing',
      tokens: [
        { name: 'space-2', value: '8px', type: 'spacing' },
        { name: 'space-4', value: '16px', type: 'spacing' },
      ],
    },
  ],
};

describe('generateTokenSection', () => {
  it('generates markdown tables per category', () => {
    const section = generateTokenSection(TOKENS);
    expect(section).toContain('### Colors');
    expect(section).toContain('| Token | Value | Type | Comment |');
    expect(section).toContain('`color-primary`');
    expect(section).toContain('#0066FF');
    expect(section).toContain('### Spacing');
    expect(section).toContain('`space-2`');
  });

  it('includes BEGIN and END markers', () => {
    const section = generateTokenSection(TOKENS);
    expect(section).toContain('<!-- BEGIN AUTOGENERATED TOKENS');
    expect(section).toContain('<!-- END AUTOGENERATED TOKENS');
  });
});

describe('injectTokenSection', () => {
  it('replaces content between markers preserving human spec', () => {
    const doc = [
      '# Design System',
      '',
      '## Spec (human-edited)',
      '',
      'My brand colors are important.',
      '',
      '---',
      '',
      '<!-- BEGIN AUTOGENERATED TOKENS — do not edit manually -->',
      '',
      'Old tokens here',
      '',
      '<!-- END AUTOGENERATED TOKENS -->',
      '',
      '> Section regenerated automatically.',
    ].join('\n');

    const tokenSection = generateTokenSection(TOKENS);
    const result = injectTokenSection(doc, tokenSection);

    expect(result).toContain('## Spec (human-edited)');
    expect(result).toContain('My brand colors are important.');
    expect(result).toContain('color-primary');
    expect(result).not.toContain('Old tokens here');
    expect(result).toContain('> Section regenerated automatically.');
  });

  it('returns original doc when markers are missing', () => {
    const doc = '# No markers here';
    const result = injectTokenSection(doc, generateTokenSection(TOKENS));
    expect(result).toBe(doc);
  });
});

describe('parseTokensJson', () => {
  it('parses any valid JSON (type assertion)', () => {
    const json = JSON.stringify(TOKENS);
    const result = parseTokensJson(json);
    expect(result.categories).toHaveLength(2);
  });
});

describe('renderFullTokenDoc', () => {
  it('end-to-end: existing doc + tokens JSON → updated doc', () => {
    const doc = [
      '# DS',
      '',
      '<!-- BEGIN AUTOGENERATED TOKENS — do not edit manually -->',
      '<!-- END AUTOGENERATED TOKENS -->',
    ].join('\n');

    const tokensJson = JSON.stringify(TOKENS);
    const result = renderFullTokenDoc(doc, tokensJson);

    expect(result).toContain('color-primary');
    expect(result).toContain('#0066FF');
    expect(result).toContain('# DS');
  });
});
