export interface TokenCategory {
  name: string;
  description?: string | undefined;
  tokens: TokenEntry[];
}

export interface TokenEntry {
  name: string;
  value: string;
  type:
    | 'color'
    | 'spacing'
    | 'font-size'
    | 'font-weight'
    | 'border-radius'
    | 'shadow'
    | 'z-index'
    | 'opacity'
    | 'transition';
  comment?: string | undefined;
}

export interface TokenFile {
  categories: TokenCategory[];
}

const BEGIN_MARKER = '<!-- BEGIN AUTOGENERATED TOKENS';
const END_MARKER = '<!-- END AUTOGENERATED TOKENS';

export function generateTokenSection(file: TokenFile): string {
  const lines: string[] = [BEGIN_MARKER, ' — do not edit manually -->', ''];

  for (const category of file.categories) {
    lines.push(`### ${category.name}`, '');
    if (category.description) {
      lines.push(`> ${category.description}`, '');
    }
    lines.push('| Token | Value | Type | Comment |', '|-------|-------|------|---------|');

    for (const token of category.tokens) {
      const comment = token.comment ?? '';
      lines.push(`| \`${token.name}\` | \`${token.value}\` | ${token.type} | ${comment} |`);
    }
    lines.push('');
  }

  lines.push(END_MARKER, '');
  return lines.join('\n');
}

export function injectTokenSection(docContent: string, tokenSection: string): string {
  const beginIdx = docContent.indexOf(BEGIN_MARKER);
  const endIdx = docContent.indexOf(END_MARKER);

  if (beginIdx === -1 || endIdx === -1) {
    return docContent;
  }

  const before = docContent.slice(0, beginIdx);
  const after = docContent.slice(endIdx + END_MARKER.length);
  const endLine = after.startsWith('\n') ? after : `\n${after}`;

  return `${before}${tokenSection}${END_MARKER}${endLine}`;
}

export function parseTokensJson(raw: string): TokenFile {
  const parsed = JSON.parse(raw) as TokenFile;
  return parsed;
}

export function renderFullTokenDoc(existingDoc: string, tokensJson: string): string {
  const tokenFile = parseTokensJson(tokensJson);
  const tokenSection = generateTokenSection(tokenFile);
  return injectTokenSection(existingDoc, tokenSection);
}
