export interface TraceabilityNode {
  number: number;
  type: 'requirement' | 'issue' | 'test' | 'bug' | 'pr' | 'release';
  title: string;
  url?: string | undefined;
}

export interface TraceabilityEdge {
  from: number;
  to: number;
  label: 'closes' | 'tests' | 'reports' | 'fixes' | 'releases';
}

export interface TraceabilityGraph {
  nodes: TraceabilityNode[];
  edges: TraceabilityEdge[];
}

export function parseTraceabilityRefs(issueBody: string): {
  closes: number[];
  tests: number[];
  bug: number[];
} {
  const closes: number[] = [];
  const tests: number[] = [];
  const bugs: number[] = [];

  const closesMatches = issueBody.matchAll(/Closes\s+#(\d+)/gi);
  for (const match of closesMatches) {
    closes.push(Number(match[1]));
  }

  const testsMatches = issueBody.matchAll(/<!--\s*tests:\s*([^>]+)-->/gi);
  for (const match of testsMatches) {
    const nums = match[1]?.match(/#(\d+)/g) ?? [];
    for (const num of nums) {
      tests.push(Number(num.replace('#', '')));
    }
  }

  const bugMatches = issueBody.matchAll(/<!--\s*bug:\s*#(\d+)\s*-->/gi);
  for (const match of bugMatches) {
    bugs.push(Number(match[1]));
  }

  return { closes, tests, bug: bugs };
}

export function buildTraceabilityGraph(
  issues: {
    number: number;
    title: string;
    body: string | null;
    labels: string[];
  }[],
): TraceabilityGraph {
  const nodes: TraceabilityNode[] = [];
  const edges: TraceabilityEdge[] = [];
  const nodeSet = new Set<number>();

  function addNode(number: number, type: TraceabilityNode['type'], title: string): void {
    if (nodeSet.has(number)) return;
    nodes.push({ number, type, title });
    nodeSet.add(number);
  }

  for (const issue of issues) {
    const isBug = issue.labels.includes('bug');
    const isTest = issue.labels.includes('testing');
    const isDocs = issue.labels.includes('documentation');
    const type: TraceabilityNode['type'] = isBug
      ? 'bug'
      : isTest
        ? 'test'
        : isDocs
          ? 'requirement'
          : 'issue';

    addNode(issue.number, type, issue.title);

    const refs = parseTraceabilityRefs(issue.body ?? '');
    for (const closesNumber of refs.closes) {
      addNode(closesNumber, 'issue', `Issue #${String(closesNumber)}`);
      edges.push({ from: issue.number, to: closesNumber, label: 'closes' });
    }
    for (const testNumber of refs.tests) {
      addNode(testNumber, 'test', `Test #${String(testNumber)}`);
      edges.push({ from: testNumber, to: issue.number, label: 'tests' });
    }
    for (const bugNumber of refs.bug) {
      addNode(bugNumber, 'bug', `Bug #${String(bugNumber)}`);
      edges.push({ from: bugNumber, to: issue.number, label: 'reports' });
    }
  }

  return { nodes, edges };
}

export function renderTraceabilityGraph(graph: TraceabilityGraph): string {
  const lines: string[] = [
    '# Traceability / Trazabilidad',
    '',
    '> Generated by ideal-guacamole Docs agent.',
    '> req → issue → test → bug → PR → release',
    '',
    '## Nodes',
    '',
    '| # | Type | Title |',
    '|---|------|-------|',
    ...graph.nodes.map((node) => `| #${String(node.number)} | ${node.type} | ${node.title} |`),
    '',
    '## Links',
    '',
    ...graph.edges.map(
      (edge) => `| #${String(edge.from)} | → ${edge.label} → | #${String(edge.to)} |`,
    ),
    '',
  ];

  return lines.join('\n');
}
